[tool.poetry]
name = "atek_main"
version = "0.1.2"
description = ""
authors = ["JediHero <hansen.rusty@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
sshtunnel = "^0.1.5"
pandas = "^1.0.5"
numpy = "^1.19.1"
cytoolz = "^0.10.1"
altair = "^4.1.0"
mysql-connector-python = "^8.0.21"
paramiko = "^2.7.1"
jupyter = "^1.0.0"
pymysql = "^0.10.0"
tabulate = "^0.8.7"
openpyxl = "^3.0.4"
python-dotenv = "^0.14.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
