[tool.poetry]
name = "exclock"
version = "0.2.6.1"
description = "exclock is a cui extended timer."
readme = "Readme.rst"
keywords = ["timer", "clock", "notification",]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Terminals",
    "Topic :: Utilities",
]
authors = ["yassu <yasu0320.dev@gmail.com>"]
repository = "https://gitlab.com/yassu/exclock"
license = "Apache-2.0"

[[tool.poetry.source]]
name = 'private'
url = 'http://example.com/simple'

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
python-vlc = "*"
json5 = "*"
tqdm = "*"
PyContracts = "^1.8.12"

[tool.poetry.dev-dependencies]
flake8 = "*"
freezegun = "*"
invoke = "*"
ipython = "*"
isort = "*"
mypy = "*"
py-term = "*"
pytest = "*"
pytest-cov = "*"
typing-extensions = "*"
yapf = "*"

[tool.poetry.scripts]
exclock = 'exclock.main:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
