[tool.poetry]
name = "rfq"
version = "0.1.1"
description = "Simple language-agnostic message queues: tools, conventions, examples"
authors = ["Robofarm <hello@robofarm.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
hiredis = "^1.0.1"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.1"

[tool.poetry.scripts]
rfq = "rfq.scripts.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
