[tool.poetry]
name = "pipetoys"
version = "0.3.1"
description = "Pythonic pipelines."
license = "ISC"
readme = "README.md"
authors = ["SeparateRecords <me@rob.ac>"]

[tool.poetry.dependencies]
python = "^3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
