[tool.poetry]
name = "jotter"
version = "0.1.3"
description = "Note taking and syncing utility."
authors = ["Figglewatts <figglewatts@hotmail.co.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
appdirs = "^1.4.4"
marshmallow = "^3.7.1"
pyyaml = "^5.3.1"
gitpython = "^3.1.7"

[tool.poetry.dev-dependencies]
pylint = "^2.5.3"
yapf = "^0.30.0"
pytest = "^5.4.3"
pytest-cov = "^2.10.0"

[tool.poetry.scripts]
jotter = 'jotter.cli:jotter'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
