[tool.poetry]
name = "pyminigasket"
packages = [
    { include = "minigasket" },
]
version = "0.2.0"
description = "A tiny library for dataflow programming."
authors = ["Coriander V. Pines <contact@corianderpines.org>"]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://gitlab.com/cvpines/pyminigasket"
repository = "https://gitlab.com/cvpines/pyminigasket"
documentation = "https://gitlab.com/cvpines/pyminigasket/-/blob/stable/README.md"
keywords = ["dataflow", "flow"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
coverage = "^5.2.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
